[env:uno]
platform = atmelavr
board = uno
framework = arduino
; Prefer local libs under ./lib
lib_extra_dirs = ./lib
lib_deps = 
    Wire                               # I2C communication
    OneWire                            # Temperature sensors
    DallasTemperature                  # DS18B20 support
    br3ttb/PID@^1.2.1                  # PID controller library
    TimerOne                           # Timer1 library for precise timing
    RBDimmer                           # Dimming control for Triac
monitor_speed = 115200
build_flags = 
    -DARDUINO_SENSOR_CONTROLLER
    -DARDUINO_ARCH_AVR
    -DALL_DIMMERS=13

